# -*- coding: utf-8 -*-
"""Project1_Streamlit_Advertisement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u70aLaYrMp05m-7suDisZS6CkO_CxKvK
"""

#Import packages
import streamlit as st
import pandas as pd
import sklearn as skl
import numpy as np
from sklearn.linear_model import LinearRegression

# Read the CSV file into a DataFrame object
df = pd.read_csv('AdvertisingProject.csv', index_col='Unnamed: 0')

# Prepare the data
feature_cols = ['TV', 'Radio', 'Newspaper']
X = df[feature_cols]
Y = df['Sales']

# Train the model
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state=1)

# Choose the model as Linear Regression
model = LinearRegression()
model.fit(X_train, Y_train)

st.write("""
# Simple Advertising Sales Prediction App
This app predicts the **Sales Performance** for different advertisement types!
""")

st.sidebar.header('User Input Parameters')

def user_input_features():
    TV = st.sidebar.slider('TV', 0.7, 296.4, 10)
    Radio = st.sidebar.slider('Radio', 0, 49.6, 10)
    Newspaper = st.sidebar.slider('Newspaper', 0.3, 114.0, 10)
    
    data = {'TV': TV,
            'Radio': Radio,
            'Newspaper': Newspaper}
    features = pd.DataFrame(data, index=[0])
    return features

user = user_input_features()

st.subheader('User Input parameters')
st.write(user)

prediction = model.predict(user)

st.subheader('Prediction')
st.write(prediction)